---
labelPrefix: convex

nameOverride: ""
fullnameOverride: ""

namespace:
  system: convex-system

deployments: []

image:
  registry: docker.horse
  pullPolicy: IfNotPresent
  pullSecrets: []

usher:
  enabled: true
  extraEnv: []
  replicas: 2
  listen: :8080
  image:
    repository: vapronva/concave/usher
    tag: ""
  bigbrainUrl: ""
  preferredNode: ""
  nodes: []
  resources: {}
  pdb:
    enabled: true

bigbrain:
  enabled: true
  extraEnv: []
  replicas: 1
  listen: :8081
  image:
    repository: vapronva/concave/bigbrain
    tag: ""
  insightsRingCap: 50000
  reconcileInterval: 2s
  promoteDebounce: 3
  failback:
    enabled: true
    stability: 15s
    warmthLag: 5000000000
  preferredNode: ""
  nodes: []
  metricsApiserver:
    enabled: true
    port: 6443
  resources: {}
