---
labelPrefix: convex

namespace:
  system: convex-system

deployments: []

image:
  registry: docker.horse
  pullPolicy: IfNotPresent

usher:
  enabled: true
  replicas: 2
  listen: ":8080"
  image:
    repository: vapronva/concave/usher
    tag: ""
  bigbrainUrl: ""
  preferredNode: ""
  nodes: []
  resources: {}

bigbrain:
  enabled: true
  replicas: 1
  listen: :8081
  image:
    repository: vapronva/concave/bigbrain
    tag: ""
  insightsRingCap: 50000
  reconcileInterval: 2s
  promoteDebounce: 3
  failback:
    enabled: false
    stability: 15s
    warmthLag: 5000000000
  preferredNode: ""
  nodes: []
  rbac:
    create: true
  resources: {}
