---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "convex.leaderName" . }}
  labels:
    {{- include "convex.componentLabels" (dict "ctx" . "component" "leader") | nindent 4 }}

spec:
  selector:
    {{- include "convex.componentSelectorLabels" (dict "ctx" . "component" "leader") | nindent 4 }}
  ports:
    - { name: cloud, port: 3210, targetPort: cloud }
    - { name: site, port: 3211, targetPort: site }

{{- if gt (int .Values.ha.standbyReplicas) 0 }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "convex.followerName" . }}
  labels:
    {{- include "convex.componentLabels" (dict "ctx" . "component" "follower") | nindent 4 }}

spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "convex.componentSelectorLabels" (dict "ctx" . "component" "follower") | nindent 4 }}
  ports:
    - { name: cloud, port: 3210, targetPort: cloud }
{{- end }}
